name: CI

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  # 1. Linting & Testing job
  lint-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend  # backend 폴더에서 실행

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies with pnpm
        run: |
          npm install -g pnpm
          pnpm install

      - name: Lint the code
        run: pnpm exec eslint src --ext .ts

      - name: Run tests
        run: pnpm exec jest

  # 2. Build job
  build:
    runs-on: ubuntu-latest
    needs: lint-test
    defaults:
      run:
        working-directory: ./backend  # backend 폴더에서 실행

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies with pnpm
        run: |
          npm install -g pnpm
          pnpm install

      - name: Build the project
        run: pnpm build
